name: mobileapplication
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0
  just_audio: ^0.9.46

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/correct.mp3
    - assets/audio/wrong.mp3
    - assets/images/compare.png
    - assets/images/order.png
    - assets/images/compose.png
